[build]
builder = "NIXPACKS"
buildCommand = "NODE_ENV=development npm install && npm run build"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
